name: Vip 8 pipeline
on: [push]
jobs:
    Pipeline:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Download dependencies
              run: lein deps
            - name: Build release
              run: lein uberjar
            - name: Run Tests
              run: lein test
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  files: |
                      *.jar
